-- ============================================================
-- project_test.sql: B+ Tree Index Functionality Test
-- ============================================================

-- 0. Setup: create the employees table
CREATE TABLE employees (
    id INT,
    name VARCHAR(100),
    department VARCHAR(50),
    salary INT
);

-- 1. Load data from the CSV file generated by generate_data.py
LOAD DATA INFILE 'data.csv' INTO TABLE employees;

-- ============================================================
-- Test 1: Full table scan before any index (baseline)
-- ============================================================
SELECT * FROM employees WHERE salary = 75000;
-- Expected: returns rows with salary exactly 75000

SELECT id, name FROM employees WHERE salary > 50000 AND salary < 80000;
-- Expected: returns multiple rows

-- ============================================================
-- Test 2: Create an index
-- ============================================================
CREATE INDEX idx_salary ON employees (salary);
-- Builds B+ tree on salary column

-- ============================================================
-- Test 3: Equality search using index
-- ============================================================
SELECT * FROM employees WHERE salary = 52000;
-- Expected: rows with salary 52000 (must use index, not full scan)
SELECT * FROM employees WHERE salary = 300000;
-- Expected: empty set (value does not exist)

-- ============================================================
-- Test 4: Range search using index (leaf node links)
-- ============================================================
SELECT * FROM employees WHERE salary > 60000 AND salary < 80000;
-- Expected: all rows in that range, output ordered by salary
SELECT * FROM employees WHERE salary > 90000;
-- Expected: rows with salary > 90000
SELECT * FROM employees WHERE salary < 60000;
-- Expected: rows with salary < 60000

-- ============================================================
-- Test 5: Edge cases (robustness)
-- ============================================================

-- 5.1 Empty table index
CREATE TABLE empty_table (x INT);
CREATE INDEX idx_empty ON empty_table (x);
SELECT * FROM empty_table WHERE x = 1;
-- Expected: empty result

-- 5.2 Fallback to full table scan when no index exists
SELECT * FROM employees WHERE department = 'HR';
-- Expected: correct rows, system must not crash, should fall back to full scan

-- ============================================================
-- End of test
-- ============================================================